import { Clock3, Mail, ShieldCheck } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Link, useSearchParams, useNavigate } from 'react-router-dom';
import { HelpBreadcrumbs } from '@/components/help/HelpBreadcrumbs';
import { useToast } from '@/components/providers';
import { Badge, Button, Card, Field, Switch } from '@/components/ui';
import { helpApi } from '@/lib/help-api';
import { useApi } from '@/lib/use-api';
import type { HelpSupportCategory } from '@/lib/help-types';

const categories: Array<{ value: HelpSupportCategory; label: string }> = [
  { value: 'account', label: 'Account & sign in' }, { value: 'agents', label: 'Agents' }, { value: 'knowledge', label: 'Knowledge' }, { value: 'conversations', label: 'Conversations' }, { value: 'integrations', label: 'Integrations' }, { value: 'deploy', label: 'Deploy' }, { value: 'workspace', label: 'Workspace' }, { value: 'billing', label: 'Billing' }, { value: 'security', label: 'Security' }, { value: 'other', label: 'Other' },
];

export function HelpSupportPage() {
  const { pushToast } = useToast(); const navigate = useNavigate(); const [searchParams] = useSearchParams(); const sourcePath = searchParams.get('from') || '/help'; const home = useApi(() => helpApi.home(), []); const requests = useApi(() => helpApi.supportRequests(), []);
  const [category, setCategory] = useState<HelpSupportCategory>('other'); const [subject, setSubject] = useState(''); const [message, setMessage] = useState(''); const [diagnostics, setDiagnostics] = useState(true); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (subject.trim().length < 3 || message.trim().length < 10) { pushToast('Add a subject and a little more detail', 'error'); return; } setSaving(true); try { const created = await helpApi.createSupportRequest({ category, subject: subject.trim(), message: message.trim(), contextPath: sourcePath, includeDiagnostics: diagnostics, diagnostics: diagnostics ? { userAgent: navigator.userAgent, language: navigator.language, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone } : {} }); pushToast('Support request submitted'); navigate(`/help/support/${created.id}`); } catch (error) { pushToast(error instanceof Error ? error.message : 'Unable to send support request', 'error'); } finally { setSaving(false); } }
  return <div className="page help-page"><HelpBreadcrumbs items={[{ label: 'Help', to: '/help' }, { label: 'Contact support' }]} /><div className="help-support-layout"><section><div className="help-section-heading"><div><h2>Contact support</h2><p>Send a support request without leaving Northstar.</p></div></div>{home.data ? <Card className="help-support-destination"><Mail /><div><strong>Support destination</strong><span>{home.data.support.email}</span>{home.data.support.externalUrl ? <a href={home.data.support.externalUrl} target="_blank" rel="noreferrer">Open external support resource</a> : null}</div></Card> : null}<Card className="help-support-form"><form onSubmit={submit}><Field label="Category"><select value={category} onChange={(event) => setCategory(event.target.value as HelpSupportCategory)}>{categories.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></Field><Field label="Subject"><input value={subject} maxLength={200} onChange={(event) => setSubject(event.target.value)} placeholder="Short summary of the problem" /></Field><Field label="Description" hint="Do not include passwords, tokens, API keys, Meta credentials, full conversations, or customer knowledge."><textarea rows={7} maxLength={8000} value={message} onChange={(event) => setMessage(event.target.value)} placeholder="What were you trying to do, and what happened?" /></Field><Switch checked={diagnostics} onChange={setDiagnostics} label="Include safe diagnostic context" description="Adds route, browser, language, and timezone only. Secrets are excluded." /><div className="help-support-form__safe"><ShieldCheck /><span>Northstar filters diagnostic fields and does not automatically collect tokens, passwords, API keys, Meta credentials, conversation contents, or customer knowledge.</span></div><Button type="submit" disabled={saving}>{saving ? 'Submitting…' : 'Send support request'}</Button></form></Card></section><aside className="help-request-history"><h3>My requests</h3>{requests.loading ? <p>Loading requests…</p> : requests.data?.length ? requests.data.map((item) => <Link key={item.id} to={`/help/support/${item.id}`}><span><strong>{item.subject}</strong><small><Clock3 /> {new Date(item.createdAt).toLocaleString()}</small></span><Badge tone={item.status === 'closed' ? 'success' : 'brand'}>{item.status}</Badge></Link>) : <Card className="help-request-history__empty">No support requests yet.</Card>}</aside></div></div>;
}
